### PR TITLE
Fix typo in KafkaListenerErrorHandler class description

### PR DESCRIPTION
**Pull request by cbismuth**
This PR fixes a very minor typo in the `KafkaListenerErrorHandler` class description to get better code rendering.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cbismuth Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=947)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=947) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cbismuth Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=947)!

**Comment by artembilan** [comment]
@cbismuth ,

Thank you for the contribution.
Looking forward for more!

**Comment by cbismuth** [comment]
You're welcome @artembilan, I'll try to do so :+1:

**Pull request merged**
