### PR TITLE
GH-2692: to be compatible with @Nested annotation

### PR DESCRIPTION
**Pull request by violetbeach**
reoslves #2692

### CODE REVIEW

**Comment by artembilan** [comment]
Can we understand, please, which one your two PRs is valid: https://github.com/spring-projects/spring-kafka/pull/2693?
And close one of them in favor of another.

**Comment by violetbeach** [comment]
> 

Oh, thank you. I couldn't decide which code would be better, so I posted both! 🤣 I think this PR code is better, so I'll close the other PR.

**Review by artembilan — CHANGES_REQUESTED** [review]
Any chances to have a new test confirming the problem and the fix you propose?

**Comment by violetbeach** [comment]
> Any chances to have a new test confirming the problem and the fix you propose?

Added test code. And can also add the following test code to ensure that the context is cached correctly.
- https://github.com/spring-projects/spring-boot/issues/30884

I think it's too much, and I've decided that @Autowired works in a class with @Nested, and it doesn't cause any problems.

_Feel free to let me know if you need anything else! Thank you. 👍_

**Review by artembilan — CHANGES_REQUESTED** [review]
>  And can also add the following test code to ensure that the context is cached correctly.

Yes, please, add that test as well.
Better to have it all covered.
From what I see with your changes about `TestContextAnnotationUtils`, I'm not sure how that fixes a caching problem. It might need a dedicated issue and another fix.

Thanks

**Comment by violetbeach** [comment]
> Yes, please, add that test as well.

I added a test.
Let me know if you need anything else!

Thanks

**Review by artembilan — CHANGES_REQUESTED** [review]
Please, see if you can fix Checkstyle violations:
```
 > Task :spring-kafka-test:checkstyleTest FAILED
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java:1: Line does not match expected header line of '^\Q/*\E$'. [RegexpHeader]
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java:5:1: 'org.springframework.beans.factory.annotation.Autowired' should be separated from previous imports. [ImportOrder]
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java:11:1: Wrong order for 'java.util.List' import. [ImportOrder]
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java:14:1: Wrong order for 'org.assertj.core.api.Assertions.assertThat' import. [ImportOrder]
Error: eckstyle] [ERROR] /home/runner/work/spring-kafka/spring-kafka/spring-kafka-test/src/test/java/org/springframework/kafka/test/condition/WithNestedClassContextTests.java:15:83: Using a static member import should be avoided - org.springframework.kafka.test.condition.WithNestedClassContextTests.Config. 
```
You can run `./gradlew check` locally to see those problems.

**Comment by violetbeach** [comment]
> Please, see if you can fix Checkstyle violations:

Oh, I see. I modified it. sorry 🙇

Thanks

**Comment by artembilan** [comment]
@violetbeach ,

thank you very much for contribution; looking forward for more!

**Pull request merged**
