### PR TITLE
GH-134: Ignore flush() if 'producer' is not inititalized yet

### PR DESCRIPTION
**Pull request by stepio**
Fix for the issue:
https://github.com/spring-projects/spring-kafka/issues/134

### CODE REVIEW

**Comment by artembilan** [comment]
Yeah... `master` again?

Please, make a top-level branch for the issue, e.g. `GH-134` and commit and push from there.
Plus consider some simple test-case for better coverage.
And add your name to the `@author` list finally! :smile: 

Thank you for so quick turnaround!

**Comment by stepio** [comment]
> Yeah... master again?

I know, I know - created a branch, but forgot to checkout into it - understood this only after pushing :)

I'm a bit lost regarding the change:
1. `IllegalStateException` - already discussed, but "disliked" by @garyrussell 
2. Just ignoring - I also thought this to be a good option originally + it's simpler (to need to compose a human-readable exception message).
3. Assert... Yeah, maybe, why not? But will they work if assertions are disabled?

> Plus consider some simple test-case for better coverage.

Sure, agree

**Comment by artembilan** [comment]
You have to just add:
```
Assert.state(this.producer != null, "'producer' must not be null for flushing.")
```
before `this.producer.flush();`
Exactly that `state` throws `IllegalStateException`.
That was my point.

I don't see anything good in the promotion of the wrong way to use our API, if we just ignore the `null` fact and let to build undesired state machine in the target application.

Your arguments to ignore the `NPE`?

**Comment by stepio** [comment]
I don't see any business case when this swallowing may be necessary and your reasoning is good enough, so Ok for me

**Pull request closed without merging**
