### PR TITLE
GH-3057: ReactiveKafkaConsumerTemplate missing receiveBatch method

### LINKED ISSUE #3057: ReactiveKafkaConsumerTemplate missing receiveBatch method
**Expected Behavior**

There is a ReactiveKafkaConsumerTemplate#receiveBatch  method.

**Current Behavior**

The ReactiveKafkaConsumerTemplate class is missing the KafkaReceiver#receiveBatch method wrapper

**Context**

### PR DESCRIPTION
**Pull request by marcusvoltolim**
* Adding wrapper method `receiveBatch` in ReactiveKafkaConsumerTemplate.

Closes #3057

### CODE REVIEW

**Comment by sobychacko** [comment]
@marcusvoltolim Why are you changing the batch semantics in the API? The `batchReceives` has a return of `Flux<Flux<ReceiverRecord<K, V>>>` and you are flat mapping it. Why can't we let the user make that decision?

**Comment by marcusvoltolim** [comment]
> @marcusvoltolim Why are you changing the batch semantics in the API? The `batchReceives` has a return of `Flux<Flux<ReceiverRecord<K, V>>>` and you are flat mapping it. Why can't we let the user make that decision?

I used `receiveAutoAck` as an example, which does the same thing.

**Comment by sobychacko** [comment]
Thanks. But, since we are explicitly dealing with a batch API here, producing the output in the raw format might be beneficial without that flatmap operation.

**Comment by marcusvoltolim** [comment]
> flatmap operatio



> Thanks. But, since we are explicitly dealing with a batch API here, producing the output in the raw format might be beneficial without that flatmap operation.

I agree, and removed this concatMap.

**Comment by sobychacko** [comment]
Any chance you can verify the new API via a unit or integration test?

**Comment by marcusvoltolim** [comment]
> Any chance you can verify the new API via a unit or integration test?

I try make this test!

**Comment by sobychacko** [comment]
@marcusvoltolim Any updates? We have a release next week, and if you want this to be part of that release, then this needs to be addressed sooner so we can progress on the PR.

**Pull request merged**
