### PR TITLE
Fix streams docs

### PR DESCRIPTION
**Pull request by daehokimm**
* Fix wrong prop keys
* Add `BOOTSTRAP_SERVERS_CONFIG`(boostrap.servers) configs
* Fix KStreams example to executable.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@daehokimm Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1444)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1444) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@daehokimm Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1444)!

**Comment by daehokimm** [comment]
what is cause to fail to build. 
I only fixed the docs.. 🤔

**Comment by garyrussell** [comment]
Don't worry about that; there is an intermittent Gradle bug that we are trying to figure out.

Thanks for the contribution.

**Comment by artembilan** [comment]
@daehokimm ,

Thank you for contribution; looking forward for more!

**Pull request merged**
