### PR TITLE
Add methods receiving ProducerRecord to ProducerListener

### PR DESCRIPTION
**Pull request by endSly**
Also added default implementations to ProducerRecord methods and deprecated the ProducerRecordAdapter

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@endSly Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=681)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=681) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@endSly Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=681)!

**Comment by artembilan** [comment]
@endSly ,

Thank you for the contribution, but would you mind to provide some explanation for reason to have this change. What the change we can see in your code, but "why?" is still a question.

Thank you for understanding.

**Comment by endSly** [comment]
Hi @artembilan ,
I need to read the record headers from the listener, and, with the current callbacks, this is not possible.

Thanks!

**Comment by garyrussell** [comment]
I think it's a valid change, but we won't be able to back-port it as-is to 2.1 because it's a breaking change. If you need this in a 2.1.x release it would have to be implemented in a non-breaking way.

**Comment by endSly** [comment]
@garyrussell, correct me if I'm wrong, but, it should be backward compatible. Adding new methods to `ProducerListener` with a default implementation does not break the previous contract.

**Comment by garyrussell** [comment]
That's true, the contract is ok, but you've changed the template to unconditionally call the new method.

**Comment by garyrussell** [comment]
Doh; sorry - hadn't looked at the default impls.

**Comment by garyrussell** [comment]
@endSly If you would like to go ahead and deprecate that method (something like `* @deprecated it is no longer necessary to implement this method`), and add your name to the `@author` tags for the affected classes, we will go ahead and merge/cherry-pick this PR).

Thanks for the contribution.

**Comment by endSly** [comment]
@garyrussell branch updated.

Thanks!

**Comment by garyrussell** [comment]
Merged as 7a1653b5dd059006c6e4b6508f7cbb89be6baad6 and cherry-picked to 2.1.x as 221ead50fae291dc749af4436990549396ac7de3

**Comment by nicklaseklund** [comment]
@endSly @garyrussell 

In the current documentation: https://docs.spring.io/spring-kafka/docs/2.4.1.RELEASE/reference/html/ it says that "isInterestedInSuccess" should be set if we want to get the onSuccess callback.

But in this commit it has been removed and deprecated. 

Please update the documentation.

**Comment by garyrussell** [comment]
Thanks - https://github.com/spring-projects/spring-kafka/pull/1364

**Pull request closed without merging**
