### PR TITLE
fix getHighestOffsetRecords for ack

### PR DESCRIPTION
**Pull request by realcbb**
One poll messages may have data from different topics, so getHighestOffsetRecords should base on TopicPartition rather than partition only. I create a PR, please check it.

### CODE REVIEW

**Comment by artembilan** [comment]
Good catch!

Would you mind to supply your fix with the test-case to cover the code and protect ourselves in the future?

Thanks

**Comment by pivotal-issuemaster** [comment]
@realcbb Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=344)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=344) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@realcbb Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=344)!

**Comment by realcbb** [comment]
Check the test case please. @artembilan

**Pull request closed without merging**
