### PR TITLE
GH-3076: Set `batchFailed` state in `ListenerConsumer` even if no `commonErrorHandler` is configured

### PR DESCRIPTION
**Pull request by rroesch1**
This PR is naïve approach to solve #3076 (i am not sure about possible side effects/consequences of this change)

### CODE REVIEW

**Comment by rroesch1** [comment]
@pivotal-cla This is an Obvious Fix

**Review by artembilan — CHANGES_REQUESTED** [review]
The fix looks good!

Any chances we can have a unit test to cover such a situation?

And from there the fix won't be so `obvious`, so consider to sign the CLA, please.

**Comment by rroesch1** [comment]
* Sorry for the late feedback but i had to clarify the CLA requirement with my employer.  My contributions should now be covered by a Corporate CLA.
* I added a unit test which should cover the situation described in #3076 (thus it's probably no longer an obvious fix)

**Review by artembilan — CHANGES_REQUESTED** [review]
Please, add your name to the `@author` list of the affected classes.

**Comment by rroesch1** [comment]
> Please, add your name to the `@author` list of the affected classes.

done

**Pull request merged**
