### PR TITLE
Add default header patterns to SimpleKafkaHeaderMapper

### PR DESCRIPTION
**Pull request by jdarc**
Fixes https://github.com/spring-projects/spring-kafka/issues/1310

### CODE REVIEW

**Comment by jdarc** [comment]
@artembilan Fixed problems reported by checkstyle... can you please explain what you mean with "Please, add your to affected classes." I checked the CONTRIBUTING.adoc but found nothing to clarify. Thank you

**Comment by garyrussell** [comment]
>@garyrussell , WDYT?

I agree.

@jdarc he meant "add your name" (to the `@author` list).

**Comment by artembilan** [comment]
Since we all agree, it looks like we need to start new `2.4` version and merge all the related changes over there already.
The Dec 6th is not around the corner though...

**Comment by garyrussell** [comment]
Yeah - I just moved the date - the 2.4.0 kafka-clients has slipped to Nov' 30.

Unfortunately, [they don't currently publish snapshots](https://issues.apache.org/jira/browse/KAFKA-2380) so we can't add a CI build, but I will push my 2.4 branch to a PR against a temporary 2.4 branch for you to review.

I have pushed a 24WIP branch and will merge this there.

**Comment by garyrussell** [comment]
Merged as 5091fdc0ecad21dba3788bbea8000a8e3e1a2958 on `24WIP`.

Thanks for the contribution!!

**Pull request closed without merging**
