### PR TITLE
Polish DestinationTopicPropertiesFactory

### PR DESCRIPTION
**Pull request by Wzy19930507**
polish `DestinationTopicPropertiesFactory` and `DestinationTopicPropertiesFactoryTests`

### CODE REVIEW

**Comment by sobychacko** [comment]
@Wzy19930507 Changes look good. Could you add a small motivation for this PR as a commit message or here? That way, it is easier to follow through, especially later on. Was there anything particularly wrong, or is it mostly cleanup?

**Comment by Wzy19930507** [comment]
@sobychacko Hi, thanks for your review and nice advice. It mostly cleanup. 
This class goes through many iterations and the code is hard to read for me.

**Comment by sobychacko** [comment]
Can you update the copyright years on the classes changed?

**Comment by sobychacko** [comment]
@Wzy19930507 Thanks for the PR. It is now merged upstream.

**Comment by Wzy19930507** [comment]
Thanks for your review!

**Pull request merged**
