### PR TITLE
GH-787: use upper-bounded wildcard in RecordFilterStrategy

### PR DESCRIPTION
**Pull request by Kirill380**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Kirill380 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=788)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=788) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by garyrussell** [comment]
Thanks for the contribution. Can you provide an example and/or test case that demonstrates how this helps.

I have been hacking around but can't figure it out (maybe not enough coffee today 😄 ).

**Comment by garyrussell** [comment]
Also, this is a breaking change, so we can't back-port it to 2.1.x.

**Comment by garyrussell** [comment]
The window for getting this into 2.2 is closing; the release candidate is due at the end of next week; please provide an example and/or test case.

**Comment by garyrussell** [comment]
Ping - one more chance to provide a test and/or example before we GA next week.

**Comment by artembilan** [comment]
Superseded with https://github.com/spring-projects/spring-kafka/pull/937

**Pull request closed without merging**
