### PR TITLE
Fixed typos in readme

### PR DESCRIPTION
**Pull request by rahilsh**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rahilsh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1505)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1505) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rahilsh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1505)!

**Comment by artembilan** [comment]
@rahilsh ,

thank you for contribution; looking forward for more!

**Comment by rahilsh** [comment]
@artembilan ,

Sure, I will have a look at issues and see if I can contribute. Also, let me know if there is anything else I can help with.

**Pull request merged**
