### PR TITLE
Kafka spring university 101

### PR DESCRIPTION
**Pull request by xodiumluma**

### CODE REVIEW

**Comment by artembilan** [comment]
@xodiumluma ,

stop pushing [PRs](https://github.com/spring-projects/spring-kafka/pull/2608) to `upstream` without any explanations. 
We may start treating this as spam and will ask GitHub to block your account.
Thanks for understanding.

**Comment by xodiumluma** [comment]
Hi,
Very, very sorry about this. I must have accidentally chosen the wrong branch/repo. I was studying the spring-kafka source code in my fork.
Sincerely,
xodiumluma

**Comment by xodiumluma** [comment]
I think to prevent this I will stick with my non-main branch and prevent merging to main, so that this problem won't ever occur again.
If you have any tips, they are most welcome.
Once again, my **sincerest** apologies.

**Comment by xodiumluma** [comment]
Thanks @artembilan. Really appreciate the advice. :+1:

**Pull request closed without merging**
