### PR TITLE
removed StreamsConfig dependency from StreamsBuilderFactoryBean

### LINKED ISSUE #1162: Remove StreamsConfig References in StreamsBuilderFactoryBean

### PR DESCRIPTION
**Pull request by dharmeshjogadia**
fixes #1162

### CODE REVIEW

**Comment by garyrussell** [comment]
Thanks for the contribution, but please note the milestone it is targeted for - `2.4.M1` - so this can't be merged until `2.3` is released next month.

**Comment by artembilan** [comment]
We can start `2.4-WIP` branch and let people to contribute against it including this good code clean up which really can't be done in the current version.

**Comment by artembilan** [comment]
I think this can be merged already into the https://github.com/spring-projects/spring-kafka/tree/24WIP branch

Thanks

**Comment by garyrussell** [comment]
Merged as 55b1eb033ed48f1790b7c092a76b49d6b616de1a

Thanks for the contribution!!

**Pull request closed without merging**
