### PR TITLE
Manage log.dir in the EmbeddedKafkaBroker

### PR DESCRIPTION
**Pull request by garyrussell**
Resolves https://github.com/spring-projects/spring-kafka/issues/194

Create the temporary directory in EKB instead of the broker to avoid
`NoSuchFileException`s during shutdown.

**cherry-pick to 2.4.x, 2.3.x, 2.2.x**

### CODE REVIEW

**Comment by artembilan** [comment]
Gary, any ideas about Travis failure:
```
KafkaAdminTests > alreadyExists() FAILED

    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132

        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1796

            Caused by: kafka.common.InconsistentBrokerIdException at KafkaServer.scala:767

KafkaAdminTests > testTopicConfigs() FAILED

    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132

        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1796

            Caused by: kafka.common.InconsistentBrokerIdException at KafkaServer.scala:767

KafkaAdminTests > toggleBootstraps() FAILED

    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132

        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1796

            Caused by: kafka.common.InconsistentBrokerIdException at KafkaServer.scala:767

KafkaAdminTests > testAddTopicsAndAddPartitions() FAILED

    java.lang.IllegalStateException at DefaultCacheAwareContextLoaderDelegate.java:132

        Caused by: org.springframework.beans.factory.BeanCreationException at AbstractAutowireCapableBeanFactory.java:1796

            Caused by: kafka.common.InconsistentBrokerIdException at KafkaServer.scala:767
```
?

**Comment by garyrussell** [comment]
No; but I realize there is a problem with this if there are multiple broker instances.

**Comment by artembilan** [comment]
>  but I realize there is a problem with this if there are multiple broker instances.

I think you mean that every broker instance we start with Embedded Kafka has to have its won unique logDir?

**Comment by garyrussell** [comment]
Exactly, yes; and it **is** the cause of this problem because this test uses 3 brokers.

**Comment by garyrussell** [comment]
Force-pushed and travis is green.

**Comment by artembilan** [comment]
Cherry-picked to `2.4.x` & `2.3.x`.
Back-ported to `2.2.x` as  https://github.com/spring-projects/spring-kafka/commit/a21fdebdd7120f208f9fcfe3e382625b4660ee87 after fixing conflicts.

**Pull request merged**
