### PR TITLE
Fixes https://github.com/spring-projects/spring-kafka/issues/1226 

### PR DESCRIPTION
**Pull request by justinbaur**
Update snippet to correct return type and misspelling

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@justinbaur Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1227)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1227) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@justinbaur Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-kafka&pullRequestId=1227)!

**Comment by artembilan** [comment]
@justinbaur ,

thank you very much for the contribution; looking forward for more!

**Comment by artembilan** [comment]
... and cherry-picked to `2.2.x`

**Pull request merged**
