### PR TITLE
GH-2198: Observability Documentation

### PR DESCRIPTION
**Pull request by garyrussell**
Refactor for latest snapshots; add documentation generation.
Use NOOP registry and supplier for context.

GH-2417: Fix class tangles.

Resolves https://github.com/spring-projects/spring-kafka/issues/2417

Disable auto doc generation and polish manually.

### CODE REVIEW

**Review by artembilan — APPROVED** [review]
LGTM, but we cannot merge this yet since SF has not moved to the latest Micrometer SNAPSHOTs. I'm afraid we are going to be break downstream projects (e.g. Spring Boot) with this merge...

**Comment by garyrussell** [comment]
Good catch.

**Comment by garyrussell** [comment]
@artembilan Looks like the build failure for the new commit is due to a stale micrometer snapshot; must be cached somewhere.

**Comment by garyrussell** [comment]
Should be good to go.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-kafka/commit/d4619f03293e651bd0e94e84596a605bdff847fa after moving other Spring deps to SNAPSHOTs.

**Pull request closed without merging**
