### PR TITLE
GH-110: Commit offsets even when fetch is paused

### PR DESCRIPTION
**Pull request by martindam**

### CODE REVIEW

**Comment by artembilan** [comment]
Great!

Recall me, please, if you have signed the CLA already (https://github.com/spring-projects/spring-integration/blob/master/CONTRIBUTING.adoc) :smile: 

Would you mind to cover the issue with some test-case? As a modification to existing one would be enough. See `KafkaMessageListenerContainerTests`.

Thank you for the contribution BTW !

**Comment by artembilan** [comment]
M-m-m. The ticket is #112 , if that :wink:

**Comment by martindam** [comment]
Yeah I signed the CLA already for contributing to the spring integration framework - I assume it covers this as well? 

Will try to add some tests, but need to mock a bit to get access to the offset commits. 

DOH, yeah it is #112 :)

**Comment by martindam** [comment]
Closing in favor of https://github.com/spring-projects/spring-kafka/pull/114

**Pull request closed without merging**
