### PR TITLE
Documentation: fixup example for sending a message

### PR DESCRIPTION
**Pull request by ttrei**

### CODE REVIEW

**Comment by garyrussell** [comment]
This is invalid; the success method gets a `SendResult`. Why do you believe it should be changed?

https://github.com/spring-projects/spring-kafka/blob/cf89aeedf8994a5f74df800ab20c7d22e0f060f6/spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java#L353-L365

**Comment by ttrei** [comment]
Because otherwise the code doesn't compile :)

Here is an example from the same test file:
https://github.com/spring-projects/spring-kafka/blob/cf89aeedf8994a5f74df800ab20c7d22e0f060f6/spring-kafka/src/test/java/org/springframework/kafka/core/KafkaTemplateTests.java#L387-L392

**Comment by garyrussell** [comment]
Oops; yes; sorry about that; the first test doesn't use the specialized callback.

**Comment by garyrussell** [comment]
Thanks.

**Pull request merged**
