### PR TITLE
Upgrade to Sonarqube plugin

### PR DESCRIPTION
**Pull request by eddumelendez**
See gh-22

### CODE REVIEW

**Comment by garyrussell** [comment]
@eddumelendez Thanks for the contribution!

Can you please confirm that you have "signed" the [CLA as discussed in our contribution guidelines?](https://github.com/spring-projects/spring-kafka/blob/master/CONTRIBUTING.adoc#sign-the-contributor-license-agreement). Thanks

**Comment by eddumelendez** [comment]
@garyrussell I have signed before for spring boot but I can not find spring-kafka

**Comment by artembilan** [comment]
@eddumelendez ,

Thank you for letting us know about your Boot CLA.
No, you don't need to sign extra one.

Moreover we see your accepted PR for Spring Security :smile: 

And yes: thank you for the contribution!
Will be merged soon.

**Comment by artembilan** [comment]
Merged as https://github.com/spring-projects/spring-kafka/commit/adf6fc26806183e0914111dab7deae9335c76f8a

**Pull request closed without merging**
