### PR TITLE
GH-2282: Fix Multi RetryableTopic Same Topic

### PR DESCRIPTION
**Pull request by garyrussell**
Resolves https://github.com/spring-projects/spring-kafka/issues/2282

### CODE REVIEW

**Comment by garyrussell** [comment]
cc/ @tomazfernandes FYI - we'd appreciate a review if you have time; no rush; RC2 is scheduled in 2 weeks' time.

**Comment by tomazfernandes** [comment]
Sure @garyrussell!

The solution looks great, just one detail in the docs.

I wonder though if it'd make sense to create a `RetryTopicEndpoint` subclass so we can add the `mainListenerId` property, and whatever properties we need for retryable topics in the future, without adding complexity to the existing `Endpoint` classes and to the classes that deal with them.

WDYT?

**Comment by tomazfernandes** [comment]
Sure, looks good to me then!

**Review by tomazfernandes — APPROVED** [review]
LGTM!

**Review by artembilan — CHANGES_REQUESTED** [review]

**Pull request merged**
